//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTecUtil.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTecUtil.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user.
        /// </summary>
        public static string Comms_Cancelled_By_User {
            get {
                return ResourceManager.GetString("Comms_Cancelled_By_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - read-only.
        /// </summary>
        public static string Comms_Connected_ReadOnly {
            get {
                return ResourceManager.GetString("Comms_Connected_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected for read/write.
        /// </summary>
        public static string Comms_Connected_Writeable {
            get {
                return ResourceManager.GetString("Comms_Connected_Writeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Comms_Direction_Download {
            get {
                return ResourceManager.GetString("Comms_Direction_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Comms_Direction_Idle {
            get {
                return ResourceManager.GetString("Comms_Direction_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Comms_Direction_Upload {
            get {
                return ResourceManager.GetString("Comms_Direction_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Comms_Disconnected {
            get {
                return ResourceManager.GetString("Comms_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** End **.
        /// </summary>
        public static string Comms_Ended {
            get {
                return ResourceManager.GetString("Comms_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel&apos;s firmware version is not supported by this Programming Tool..
        /// </summary>
        public static string Comms_Firmware_Not_Supported {
            get {
                return ResourceManager.GetString("Comms_Firmware_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for logging data.
        /// </summary>
        public static string Comms_Listening {
            get {
                return ResourceManager.GetString("Comms_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: download complete..
        /// </summary>
        public static string Comms_x_Download_Complete {
            get {
                return ResourceManager.GetString("Comms_x_Download_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: upload complete..
        /// </summary>
        public static string Comms_x_Upload_Complete {
            get {
                return ResourceManager.GetString("Comms_x_Upload_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data was received from the panel..
        /// </summary>
        public static string Error_Checksum_Fail {
            get {
                return ResourceManager.GetString("Error_Checksum_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel is not responding..
        /// </summary>
        public static string Error_Download_Retries {
            get {
                return ResourceManager.GetString("Error_Download_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Download_Timeout {
            get {
                return ResourceManager.GetString("Error_Download_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving data from the panel..
        /// </summary>
        public static string Error_Downloading_Data {
            get {
                return ResourceManager.GetString("Error_Downloading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the serial port..
        /// </summary>
        public static string Error_Serial_Port {
            get {
                return ResourceManager.GetString("Error_Serial_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled because the panel is not responding..
        /// </summary>
        public static string Error_Upload_Retries {
            get {
                return ResourceManager.GetString("Error_Upload_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Upload_Timeout {
            get {
                return ResourceManager.GetString("Error_Upload_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending data to the panel..
        /// </summary>
        public static string Error_Uploading_Data {
            get {
                return ResourceManager.GetString("Error_Uploading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string File_Save_As {
            get {
                return ResourceManager.GetString("File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string No_Data {
            get {
                return ResourceManager.GetString("No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Option_Cancel {
            get {
                return ResourceManager.GetString("Option_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string PrintQueueStatus_Busy {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door open.
        /// </summary>
        public static string PrintQueueStatus_DoorOpen {
            get {
                return ResourceManager.GetString("PrintQueueStatus_DoorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrintQueueStatus_Error {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising.
        /// </summary>
        public static string PrintQueueStatus_Initialising {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Initialising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving data.
        /// </summary>
        public static string PrintQueueStatus_IOActive {
            get {
                return ResourceManager.GetString("PrintQueueStatus_IOActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for manual feed.
        /// </summary>
        public static string PrintQueueStatus_ManualFeed {
            get {
                return ResourceManager.GetString("PrintQueueStatus_ManualFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is not specified.
        /// </summary>
        public static string PrintQueueStatus_None {
            get {
                return ResourceManager.GetString("PrintQueueStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status information is unavailable.
        /// </summary>
        public static string PrintQueueStatus_NotAvailable {
            get {
                return ResourceManager.GetString("PrintQueueStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of toner.
        /// </summary>
        public static string PrintQueueStatus_NoToner {
            get {
                return ResourceManager.GetString("PrintQueueStatus_NoToner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string PrintQueueStatus_Offline {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        public static string PrintQueueStatus_OutOfMemory {
            get {
                return ResourceManager.GetString("PrintQueueStatus_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output bin is full.
        /// </summary>
        public static string PrintQueueStatus_OutputBinFull {
            get {
                return ResourceManager.GetString("PrintQueueStatus_OutputBinFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print current page.
        /// </summary>
        public static string PrintQueueStatus_PagePunt {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PagePunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper jam.
        /// </summary>
        public static string PrintQueueStatus_PaperJam {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of paper.
        /// </summary>
        public static string PrintQueueStatus_PaperOut {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper problem.
        /// </summary>
        public static string PrintQueueStatus_PaperProblem {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print queue paused.
        /// </summary>
        public static string PrintQueueStatus_Paused {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting print job.
        /// </summary>
        public static string PrintQueueStatus_PendingDeletion {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PendingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power save mode.
        /// </summary>
        public static string PrintQueueStatus_PowerSave {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PowerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string PrintQueueStatus_Printing {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string PrintQueueStatus_Processing {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string PrintQueueStatus_Ready {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrintQueueStatus_ServerUnknown {
            get {
                return ResourceManager.GetString("PrintQueueStatus_ServerUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toner low.
        /// </summary>
        public static string PrintQueueStatus_TonerLow {
            get {
                return ResourceManager.GetString("PrintQueueStatus_TonerLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: requires user action.
        /// </summary>
        public static string PrintQueueStatus_UserIntervention {
            get {
                return ResourceManager.GetString("PrintQueueStatus_UserIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for print job.
        /// </summary>
        public static string PrintQueueStatus_Waiting {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming up.
        /// </summary>
        public static string PrintQueueStatus_WarmingUp {
            get {
                return ResourceManager.GetString("PrintQueueStatus_WarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV.
        /// </summary>
        public static string Receive_Abbr {
            get {
                return ResourceManager.GetString("Receive_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SND.
        /// </summary>
        public static string Send_Abbr {
            get {
                return ResourceManager.GetString("Send_Abbr", resourceCulture);
            }
        }
    }
}
