//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTecUtil.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTecUtil.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_AspiratingDetector.
        /// </summary>
        public static string Apollo_Discovery_AspiratingDetector {
            get {
                return ResourceManager.GetString("Apollo_Discovery_AspiratingDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_CODetector.
        /// </summary>
        public static string Apollo_Discovery_CODetector {
            get {
                return ResourceManager.GetString("Apollo_Discovery_CODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_COEnvironmentalGasMonitor.
        /// </summary>
        public static string Apollo_Discovery_COEnvironmentalGasMonitor {
            get {
                return ResourceManager.GetString("Apollo_Discovery_COEnvironmentalGasMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_COHeatDetector.
        /// </summary>
        public static string Apollo_Discovery_COHeatDetector {
            get {
                return ResourceManager.GetString("Apollo_Discovery_COHeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_COPersonalProtectionMonitor.
        /// </summary>
        public static string Apollo_Discovery_COPersonalProtectionMonitor {
            get {
                return ResourceManager.GetString("Apollo_Discovery_COPersonalProtectionMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_MOST.
        /// </summary>
        public static string Apollo_Discovery_MOST {
            get {
                return ResourceManager.GetString("Apollo_Discovery_MOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_Discovery_MultiSensor.
        /// </summary>
        public static string Apollo_Discovery_MultiSensor {
            get {
                return ResourceManager.GetString("Apollo_Discovery_MultiSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_DiscoverySounder.
        /// </summary>
        public static string Apollo_DiscoverySounder {
            get {
                return ResourceManager.GetString("Apollo_DiscoverySounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_DiscoveryVoiceSounder.
        /// </summary>
        public static string Apollo_DiscoveryVoiceSounder {
            get {
                return ResourceManager.GetString("Apollo_DiscoveryVoiceSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_HeatDetector.
        /// </summary>
        public static string Apollo_HeatDetector {
            get {
                return ResourceManager.GetString("Apollo_HeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_IonisationDetector.
        /// </summary>
        public static string Apollo_IonisationDetector {
            get {
                return ResourceManager.GetString("Apollo_IonisationDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_IOUnit.
        /// </summary>
        public static string Apollo_IOUnit {
            get {
                return ResourceManager.GetString("Apollo_IOUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_ManualCallpointWithInterrupt.
        /// </summary>
        public static string Apollo_ManualCallpointWithInterrupt {
            get {
                return ResourceManager.GetString("Apollo_ManualCallpointWithInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller.
        /// </summary>
        public static string Apollo_NetworkController {
            get {
                return ResourceManager.GetString("Apollo_NetworkController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_OpticalDetectorEUR.
        /// </summary>
        public static string Apollo_OpticalDetectorEUR {
            get {
                return ResourceManager.GetString("Apollo_OpticalDetectorEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_S90_ManualCallpoint.
        /// </summary>
        public static string Apollo_S90_ManualCallpoint {
            get {
                return ResourceManager.GetString("Apollo_S90_ManualCallpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_S90_XP95_SounderController.
        /// </summary>
        public static string Apollo_S90_XP95_SounderController {
            get {
                return ResourceManager.GetString("Apollo_S90_XP95_SounderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_S90_XP95_ZoneMonitorUnit.
        /// </summary>
        public static string Apollo_S90_XP95_ZoneMonitorUnit {
            get {
                return ResourceManager.GetString("Apollo_S90_XP95_ZoneMonitorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95_BeamDetectorUSA.
        /// </summary>
        public static string Apollo_XP95_BeamDetectorUSA {
            get {
                return ResourceManager.GetString("Apollo_XP95_BeamDetectorUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95_FlameDetector.
        /// </summary>
        public static string Apollo_XP95_FlameDetector {
            get {
                return ResourceManager.GetString("Apollo_XP95_FlameDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95_HighTempHeatDetector.
        /// </summary>
        public static string Apollo_XP95_HighTempHeatDetector {
            get {
                return ResourceManager.GetString("Apollo_XP95_HighTempHeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95_MiniSwitchMonitor.
        /// </summary>
        public static string Apollo_XP95_MiniSwitchMonitor {
            get {
                return ResourceManager.GetString("Apollo_XP95_MiniSwitchMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95_MultiSensor.
        /// </summary>
        public static string Apollo_XP95_MultiSensor {
            get {
                return ResourceManager.GetString("Apollo_XP95_MultiSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_MiniPrioritySwitchMonitor.
        /// </summary>
        public static string Apollo_XP95A_MiniPrioritySwitchMonitor {
            get {
                return ResourceManager.GetString("Apollo_XP95A_MiniPrioritySwitchMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_MiniSwitchMonitor.
        /// </summary>
        public static string Apollo_XP95A_MiniSwitchMonitor {
            get {
                return ResourceManager.GetString("Apollo_XP95A_MiniSwitchMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_PrioritySwitchMonitor.
        /// </summary>
        public static string Apollo_XP95A_PrioritySwitchMonitor {
            get {
                return ResourceManager.GetString("Apollo_XP95A_PrioritySwitchMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_SounderControlModule.
        /// </summary>
        public static string Apollo_XP95A_SounderControlModule {
            get {
                return ResourceManager.GetString("Apollo_XP95A_SounderControlModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_SwitchMonitor.
        /// </summary>
        public static string Apollo_XP95A_SwitchMonitor {
            get {
                return ResourceManager.GetString("Apollo_XP95A_SwitchMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo_XP95A_SwitchMonitorIO.
        /// </summary>
        public static string Apollo_XP95A_SwitchMonitorIO {
            get {
                return ResourceManager.GetString("Apollo_XP95A_SwitchMonitorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_BeamDetector.
        /// </summary>
        public static string Cast_BeamDetector {
            get {
                return ResourceManager.GetString("Cast_BeamDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_CODetector.
        /// </summary>
        public static string Cast_CODetector {
            get {
                return ResourceManager.GetString("Cast_CODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_DoubleGangIOSingleChannelSounderController.
        /// </summary>
        public static string Cast_DoubleGangIOSingleChannelSounderController {
            get {
                return ResourceManager.GetString("Cast_DoubleGangIOSingleChannelSounderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_DoubleGangMainsIO.
        /// </summary>
        public static string Cast_DoubleGangMainsIO {
            get {
                return ResourceManager.GetString("Cast_DoubleGangMainsIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_DoubleGangMainsIOFire2HMO.
        /// </summary>
        public static string Cast_DoubleGangMainsIOFire2HMO {
            get {
                return ResourceManager.GetString("Cast_DoubleGangMainsIOFire2HMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_DoubleGangZoneMonitor.
        /// </summary>
        public static string Cast_DoubleGangZoneMonitor {
            get {
                return ResourceManager.GetString("Cast_DoubleGangZoneMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_FlameDetector.
        /// </summary>
        public static string Cast_FlameDetector {
            get {
                return ResourceManager.GetString("Cast_FlameDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_FourChannelSounderController.
        /// </summary>
        public static string Cast_FourChannelSounderController {
            get {
                return ResourceManager.GetString("Cast_FourChannelSounderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_HeatCODetector.
        /// </summary>
        public static string Cast_HeatCODetector {
            get {
                return ResourceManager.GetString("Cast_HeatCODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_HeatDetector.
        /// </summary>
        public static string Cast_HeatDetector {
            get {
                return ResourceManager.GetString("Cast_HeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_HushButton.
        /// </summary>
        public static string Cast_HushButton {
            get {
                return ResourceManager.GetString("Cast_HushButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_MCP.
        /// </summary>
        public static string Cast_MCP {
            get {
                return ResourceManager.GetString("Cast_MCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_MiniIO.
        /// </summary>
        public static string Cast_MiniIO {
            get {
                return ResourceManager.GetString("Cast_MiniIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_MultiChannelZoneMonitor.
        /// </summary>
        public static string Cast_MultiChannelZoneMonitor {
            get {
                return ResourceManager.GetString("Cast_MultiChannelZoneMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller.
        /// </summary>
        public static string Cast_NetworkController {
            get {
                return ResourceManager.GetString("Cast_NetworkController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_OpticalCODetector.
        /// </summary>
        public static string Cast_OpticalCODetector {
            get {
                return ResourceManager.GetString("Cast_OpticalCODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_OpticalDetector.
        /// </summary>
        public static string Cast_OpticalDetector {
            get {
                return ResourceManager.GetString("Cast_OpticalDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_OpticalHeatCODetector.
        /// </summary>
        public static string Cast_OpticalHeatCODetector {
            get {
                return ResourceManager.GetString("Cast_OpticalHeatCODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_OpticalHeatDetector.
        /// </summary>
        public static string Cast_OpticalHeatDetector {
            get {
                return ResourceManager.GetString("Cast_OpticalHeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_Sounder.
        /// </summary>
        public static string Cast_Sounder {
            get {
                return ResourceManager.GetString("Cast_Sounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_SounderVAD.
        /// </summary>
        public static string Cast_SounderVAD {
            get {
                return ResourceManager.GetString("Cast_SounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_VAD.
        /// </summary>
        public static string Cast_VAD {
            get {
                return ResourceManager.GetString("Cast_VAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_VoiceSounder.
        /// </summary>
        public static string Cast_VoiceSounder {
            get {
                return ResourceManager.GetString("Cast_VoiceSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_VoiceSounderVAD.
        /// </summary>
        public static string Cast_VoiceSounderVAD {
            get {
                return ResourceManager.GetString("Cast_VoiceSounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_CODetector.
        /// </summary>
        public static string CastPro_CODetector {
            get {
                return ResourceManager.GetString("CastPro_CODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_HeatDetector.
        /// </summary>
        public static string CastPro_HeatDetector {
            get {
                return ResourceManager.GetString("CastPro_HeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller.
        /// </summary>
        public static string CastPro_NetworkController {
            get {
                return ResourceManager.GetString("CastPro_NetworkController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalDetector.
        /// </summary>
        public static string CastPro_OpticalDetector {
            get {
                return ResourceManager.GetString("CastPro_OpticalDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatCODetector.
        /// </summary>
        public static string CastPro_OpticalHeatCODetector {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatCODetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatCODetectorWithToneSounder.
        /// </summary>
        public static string CastPro_OpticalHeatCODetectorWithToneSounder {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatCODetectorWithToneSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatCODetectorWithToneSounderVAD.
        /// </summary>
        public static string CastPro_OpticalHeatCODetectorWithToneSounderVAD {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatCODetectorWithToneSounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatCODetectorWithVoiceSounder.
        /// </summary>
        public static string CastPro_OpticalHeatCODetectorWithVoiceSounder {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatCODetectorWithVoiceSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatCODetectorWithVoiceSounderVAD.
        /// </summary>
        public static string CastPro_OpticalHeatCODetectorWithVoiceSounderVAD {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatCODetectorWithVoiceSounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatDetectorWithToneSounder.
        /// </summary>
        public static string CastPro_OpticalHeatDetectorWithToneSounder {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatDetectorWithToneSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatDetectorWithToneSounderVAD.
        /// </summary>
        public static string CastPro_OpticalHeatDetectorWithToneSounderVAD {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatDetectorWithToneSounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatDetectorWithVoiceSounder.
        /// </summary>
        public static string CastPro_OpticalHeatDetectorWithVoiceSounder {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatDetectorWithVoiceSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastPro_OpticalHeatDetectorWithVoiceSounderVAD.
        /// </summary>
        public static string CastPro_OpticalHeatDetectorWithVoiceSounderVAD {
            get {
                return ResourceManager.GetString("CastPro_OpticalHeatDetectorWithVoiceSounderVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - data is read-only.
        /// </summary>
        public static string Comms_Connected_ReadOnly {
            get {
                return ResourceManager.GetString("Comms_Connected_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - data may be written.
        /// </summary>
        public static string Comms_Connected_Writeable {
            get {
                return ResourceManager.GetString("Comms_Connected_Writeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Comms_Disconnected {
            get {
                return ResourceManager.GetString("Comms_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel&apos;s firmware version is not supported by this Programming Tool..
        /// </summary>
        public static string Comms_Firmware_Not_Supported {
            get {
                return ResourceManager.GetString("Comms_Firmware_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for logging data.
        /// </summary>
        public static string Comms_Listening {
            get {
                return ResourceManager.GetString("Comms_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data was received from the panel..
        /// </summary>
        public static string Error_Checksum_Fail {
            get {
                return ResourceManager.GetString("Error_Checksum_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled after too many retries..
        /// </summary>
        public static string Error_Download_Retries {
            get {
                return ResourceManager.GetString("Error_Download_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Download_Timeout {
            get {
                return ResourceManager.GetString("Error_Download_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving data from the panel..
        /// </summary>
        public static string Error_Downloading_Data {
            get {
                return ResourceManager.GetString("Error_Downloading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the serial port..
        /// </summary>
        public static string Error_Serial_Port {
            get {
                return ResourceManager.GetString("Error_Serial_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled after too many retries..
        /// </summary>
        public static string Error_Upload_Retries {
            get {
                return ResourceManager.GetString("Error_Upload_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Upload_Timeout {
            get {
                return ResourceManager.GetString("Error_Upload_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending data to the panel..
        /// </summary>
        public static string Error_Uploading_Data {
            get {
                return ResourceManager.GetString("Error_Uploading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string File_Save_As {
            get {
                return ResourceManager.GetString("File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_AddressableBase.
        /// </summary>
        public static string Hochiki_AddressableBase {
            get {
                return ResourceManager.GetString("Hochiki_AddressableBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_AddressableBeacon.
        /// </summary>
        public static string Hochiki_AddressableBeacon {
            get {
                return ResourceManager.GetString("Hochiki_AddressableBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_BaseWallSounder.
        /// </summary>
        public static string Hochiki_BaseWallSounder {
            get {
                return ResourceManager.GetString("Hochiki_BaseWallSounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_DualSwitchController.
        /// </summary>
        public static string Hochiki_DualSwitchController {
            get {
                return ResourceManager.GetString("Hochiki_DualSwitchController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_DualZoneMonitor.
        /// </summary>
        public static string Hochiki_DualZoneMonitor {
            get {
                return ResourceManager.GetString("Hochiki_DualZoneMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_HeatDetector.
        /// </summary>
        public static string Hochiki_HeatDetector {
            get {
                return ResourceManager.GetString("Hochiki_HeatDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_IonisationDetector.
        /// </summary>
        public static string Hochiki_IonisationDetector {
            get {
                return ResourceManager.GetString("Hochiki_IonisationDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_MasterAddressableBase.
        /// </summary>
        public static string Hochiki_MasterAddressableBase {
            get {
                return ResourceManager.GetString("Hochiki_MasterAddressableBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_MCP.
        /// </summary>
        public static string Hochiki_MCP {
            get {
                return ResourceManager.GetString("Hochiki_MCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_MiniZoneMonitor.
        /// </summary>
        public static string Hochiki_MiniZoneMonitor {
            get {
                return ResourceManager.GetString("Hochiki_MiniZoneMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_MultiDetector.
        /// </summary>
        public static string Hochiki_MultiDetector {
            get {
                return ResourceManager.GetString("Hochiki_MultiDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller.
        /// </summary>
        public static string Hochiki_NetworkController {
            get {
                return ResourceManager.GetString("Hochiki_NetworkController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_NonLatchingIOUnit.
        /// </summary>
        public static string Hochiki_NonLatchingIOUnit {
            get {
                return ResourceManager.GetString("Hochiki_NonLatchingIOUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_OpticalDetector.
        /// </summary>
        public static string Hochiki_OpticalDetector {
            get {
                return ResourceManager.GetString("Hochiki_OpticalDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_RelayController.
        /// </summary>
        public static string Hochiki_RelayController {
            get {
                return ResourceManager.GetString("Hochiki_RelayController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_RemoteIndicator.
        /// </summary>
        public static string Hochiki_RemoteIndicator {
            get {
                return ResourceManager.GetString("Hochiki_RemoteIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_SingleIOModule.
        /// </summary>
        public static string Hochiki_SingleIOModule {
            get {
                return ResourceManager.GetString("Hochiki_SingleIOModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_SounderController_Groups.
        /// </summary>
        public static string Hochiki_SounderController_Groups {
            get {
                return ResourceManager.GetString("Hochiki_SounderController_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochiki_SounderController_Sets.
        /// </summary>
        public static string Hochiki_SounderController_Sets {
            get {
                return ResourceManager.GetString("Hochiki_SounderController_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Option_Cancel {
            get {
                return ResourceManager.GetString("Option_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Transmitter.
        /// </summary>
        public static string QT412_Staff_Transmitter {
            get {
                return ResourceManager.GetString("QT412_Staff_Transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendant Transmitter.
        /// </summary>
        public static string QT432_Pendant_Transmitter {
            get {
                return ResourceManager.GetString("QT432_Pendant_Transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Point.
        /// </summary>
        public static string QT602_9_or_QT302RX_Callpoint {
            get {
                return ResourceManager.GetString("QT602_9_or_QT302RX_Callpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Call Point).
        /// </summary>
        public static string QT611_CallPoint {
            get {
                return ResourceManager.GetString("QT611_CallPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the device&apos;s current settings it may be necessary to open or close the special contact in order to send and verify programming data..
        /// </summary>
        public static string QT611_Callpoint_Programming_Info {
            get {
                return ResourceManager.GetString("QT611_Callpoint_Programming_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Day/Night Switch).
        /// </summary>
        public static string QT611_Day_Night_Switch {
            get {
                return ResourceManager.GetString("QT611_Day_Night_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the device&apos;s current settings it may be necessary to open or close the switch in order to send and verify programming data..
        /// </summary>
        public static string QT611_Day_Night_Switch_Programming_Info {
            get {
                return ResourceManager.GetString("QT611_Day_Night_Switch_Programming_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Monitor Point).
        /// </summary>
        public static string QT611_Monitor_Point {
            get {
                return ResourceManager.GetString("QT611_Monitor_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the device&apos;s current settings it may be necessary to open or close the isolation contact in order to send and verify programming data..
        /// </summary>
        public static string QT611_Monitor_Point_Programming_Info {
            get {
                return ResourceManager.GetString("QT611_Monitor_Point_Programming_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Output.
        /// </summary>
        public static string QT612_Relay_Output {
            get {
                return ResourceManager.GetString("QT612_Relay_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonal Indicator/Sounder.
        /// </summary>
        public static string QT613_ZI_or_QT688_2_Sounder {
            get {
                return ResourceManager.GetString("QT613_ZI_or_QT688_2_Sounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Sensor.
        /// </summary>
        public static string QT616_Fall_Sensor {
            get {
                return ResourceManager.GetString("QT616_Fall_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Point.
        /// </summary>
        public static string Quantec_Callpoint {
            get {
                return ResourceManager.GetString("Quantec_Callpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corridor Display.
        /// </summary>
        public static string Quantec_CorridorDisplay {
            get {
                return ResourceManager.GetString("Quantec_CorridorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Point.
        /// </summary>
        public static string Quantec_MonitoringPoint {
            get {
                return ResourceManager.GetString("Quantec_MonitoringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller.
        /// </summary>
        public static string Quantec_NetworkController {
            get {
                return ResourceManager.GetString("Quantec_NetworkController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Door Light.
        /// </summary>
        public static string Quantec_OverDoorLight {
            get {
                return ResourceManager.GetString("Quantec_OverDoorLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Receiver.
        /// </summary>
        public static string Quantec_RadioReceiver {
            get {
                return ResourceManager.GetString("Quantec_RadioReceiver", resourceCulture);
            }
        }
    }
}
