//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTecUtil.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTecUtil.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - data is read-only.
        /// </summary>
        public static string Comms_Connected_ReadOnly {
            get {
                return ResourceManager.GetString("Comms_Connected_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - data may be written.
        /// </summary>
        public static string Comms_Connected_Writeable {
            get {
                return ResourceManager.GetString("Comms_Connected_Writeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Comms_Disconnected {
            get {
                return ResourceManager.GetString("Comms_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel&apos;s firmware version is not supported by this Programming Tool..
        /// </summary>
        public static string Comms_Firmware_Not_Supported {
            get {
                return ResourceManager.GetString("Comms_Firmware_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for logging data.
        /// </summary>
        public static string Comms_Listening {
            get {
                return ResourceManager.GetString("Comms_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data was received from the panel..
        /// </summary>
        public static string Error_Checksum_Fail {
            get {
                return ResourceManager.GetString("Error_Checksum_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled after too many retries..
        /// </summary>
        public static string Error_Download_Retries {
            get {
                return ResourceManager.GetString("Error_Download_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Download_Timeout {
            get {
                return ResourceManager.GetString("Error_Download_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving data from the panel..
        /// </summary>
        public static string Error_Downloading_Data {
            get {
                return ResourceManager.GetString("Error_Downloading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the serial port..
        /// </summary>
        public static string Error_Serial_Port {
            get {
                return ResourceManager.GetString("Error_Serial_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled after too many retries..
        /// </summary>
        public static string Error_Upload_Retries {
            get {
                return ResourceManager.GetString("Error_Upload_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Upload_Timeout {
            get {
                return ResourceManager.GetString("Error_Upload_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending data to the panel..
        /// </summary>
        public static string Error_Uploading_Data {
            get {
                return ResourceManager.GetString("Error_Uploading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string File_Save_As {
            get {
                return ResourceManager.GetString("File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Option_Cancel {
            get {
                return ResourceManager.GetString("Option_Cancel", resourceCulture);
            }
        }
    }
}
